### ISSUE TITLE
Request: Make this available in Google Fonts

### ISSUE THREAD

**Issue by thenonhacker** [christiannaths/redacted-font#32] opened 2018-04-12 09:11 UTC
Please make Redacted Fonts available in Google Fonts!

https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by Potherca** [comment] 2018-04-14 12:33
Please search the issues before opening an issue that already exists ;-)

Duplicate of: #1

**Closed** 2021-12-02 04:36 UTC
Labels: duplicate
